### PR TITLE
Modifications cheetah v4

### PR DESCRIPTION
**Pull request by areda0**
Potential schematic modifications to the POR:
1) Resistive branch  
image
2) Comparator
image
3) Timer 
image

### CODE REVIEW

**Review by RTimothyEdwards — CHANGES_REQUESTED** [review]
This appears to supercede the previous pull request (that is, it is a new pull request instead of a commit to the previous pull request)?  It continues to have some of the same problems, e.g., ".swp" files that should not be part of the commit.

**Comment by RTimothyEdwards** [comment]
Why did you remove M19 from the comparator?  That is a change we did not discuss and have not approved.  I assume that the transistor is there to make M15 shut off at a lower voltage and lower the voltage (`vo`) at which the inverter switches.  This directly affects the hysteresis feedback loop.  Maybe with the hysteresis having been adjusted to be so large, this doesn't make any difference?

**Comment by areda0** [comment]
Yes, I didn’t observe a significant difference. My intention with this PR wasn’t to merge any changes (since there are no layout modifications here) but rather to leave these adjustments as a basis for future discussion in an upcoming Zoom call. I realize that I may have misused the purpose of PRs in this way, so I’ll close it for now and keep these changes for later discussion.

Just to clarify, this PR isn’t meant to override the previous one, which was focused on merging the TB files.

**Comment by RTimothyEdwards** [comment]
You can push a new branch without creating a PR.  Creating a PR implies that you want to merge the changes back into the main branch.

**Pull request closed without merging**
